import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

// Lazy-loaded Gemini client with safe configuration
let aiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI | null {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey || apiKey === "MY_GEMINI_API_KEY") {
      console.warn("GEMINI_API_KEY is not configured or uses placeholder value.");
      return null;
    }
    aiClient = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

// Simulated real-time device telemetry database/state
const defaultTelemetry = {
  devices: [
    { id: "Marchival Arc", score: 41.53, uptime: 42, load: "4.8K", status: "alert", type: "Node", active: true },
    { id: "Device 07", score: 41.53, uptime: 42, load: "4.8K", status: "alert", type: "Node", active: true },
    { id: "Home Hub", score: 28.78, uptime: 48, load: "2.3K", status: "operational", type: "Host", active: true },
    { id: "Device 01", score: 28.78, uptime: 88, load: "2.3K", status: "operational", type: "Host", active: true },
    { id: "Device 04", score: 28.78, uptime: 88, load: "2.3K", status: "operational", type: "Host", active: true },
    { id: "Device 02", score: 27.73, uptime: 93, load: "6.7K", status: "flow_controller", type: "Proxy", active: true },
    { id: "Device 05", score: 27.73, uptime: 93, load: "2.3K", status: "flow_controller", type: "Proxy", active: true },
    { id: "Main Server", score: 27.53, uptime: 93, load: "6.7K", status: "operational", type: "Host", active: true },
    { id: "Device 03", score: 27.53, uptime: 93, load: "2.3K", status: "alert", type: "Node", active: true },
    { id: "Device 06", score: 27.53, uptime: 93, load: "6.7K", status: "flow_controller", type: "Proxy", active: true },
  ],
  temperatureHistory: [
    { label: "Jan", value: 15 },
    { label: "Feb", value: 20 },
    { label: "Mar", value: 16 },
    { label: "Apr", value: 23 },
    { label: "May", value: 19 },
    { label: "Jun", value: 21 },
    { label: "Jul", value: 28 },
  ],
  humidityHistory: [
    { label: "Jan", value: 30 },
    { label: "Feb", value: 45 },
    { label: "Mar", value: 35 },
    { label: "Apr", value: 50 },
    { label: "May", value: 40 },
    { label: "Jun", value: 55 },
    { label: "Jul", value: 65 },
  ]
};

// Helper to emulate natural language telemetry commands cleanly in offline or fallback modes
function emulateQueryResponse(query: string, currentWidgets: any[], isFallbackMode: boolean = false) {
  let feedbackMessage = isFallbackMode
    ? "Gridify layout engine running in backup mode due to temporary upstream model load."
    : "Configured layout and analyzed metrics successfully (Offline mode).";
  
  let newWidgets = [...(currentWidgets || [])];
  let aiSummary = [
    "Temperature trends show normal cyclical variance. Check peak loads during afternoon operations.",
    "Proxy devices maintain stable active flow control states with minor load offsets.",
    "Marchival Arc is exhibiting slightly higher average node temperature latency; investigate status indicator.",
  ];

  const lowerQuery = query.toLowerCase();
  if (lowerQuery.includes("add") || lowerQuery.includes("chart") || lowerQuery.includes("create")) {
    const id = "custom_" + Date.now();
    newWidgets.push({
      id,
      title: "Dynamic Telemetry: Sensor Voltage",
      subtitle: isFallbackMode ? "Generated by backup layout engine" : "Generated by Gemini AI layout engine",
      type: "custom_chart",
      w: 2,
      h: 300,
      order: newWidgets.length + 1,
      customData: {
        labels: ["00:00", "04:00", "08:00", "12:00", "16:00", "20:00"],
        values: [3.3, 3.2, 3.4, 3.1, 3.5, 3.3],
        yAxisLabel: "Volts (V)"
      }
    });
    feedbackMessage = isFallbackMode
      ? "Added dynamic Sensor Voltage chart (emulated fallback due to temporary model demand)."
      : "Added a dynamic Sensor Voltage chart to the layout!";
    aiSummary.unshift("Dynamic telemetry configured: Voltage levels average 3.3V, showing healthy battery load.");
  } else if (lowerQuery.includes("remove") || lowerQuery.includes("delete")) {
    if (newWidgets.length > 2) {
      const removed = newWidgets.pop();
      feedbackMessage = `Removed widget: "${removed.title}" from the active workspace.`;
    } else {
      feedbackMessage = "Kept primary widgets to maintain minimum dashboard visualization integrity.";
    }
  } else if (lowerQuery.includes("summarize") || lowerQuery.includes("analyse") || lowerQuery.includes("analyze")) {
    feedbackMessage = isFallbackMode
      ? "Completed telemetry load and uptime analysis (backup mode)."
      : "Completed deeper telemetry load and uptime analysis.";
    aiSummary = [
      "Device load: Home Hub averages 2.3K loads with optimal 26.78 Sensor load values.",
      "System uptime is steady at 3h 10m aggregate uptime with zero hard reboots.",
      "No severe performance drops are registered for any of the 10 monitored operational nodes.",
    ];
  } else {
    feedbackMessage = isFallbackMode
      ? `Processed custom query: "${query}" (backup emulation)`
      : `Processed custom query: "${query}"`;
  }

  return {
    aiSummary,
    feedbackMessage,
    newWidgets,
    status: isFallbackMode ? "Nominal (Backup Mode)" : "Nominal"
  };
}

// GET initial telemetry data
app.get("/api/telemetry", (req, res) => {
  res.json(defaultTelemetry);
});

// POST endpoint to handle natural language Gemini commands
app.post("/api/gemini/command", async (req, res) => {
  const { query, currentWidgets } = req.body;

  if (!query) {
    return res.status(400).json({ error: "Missing query string." });
  }

  const ai = getGeminiClient();
  if (!ai) {
    console.log("Gemini API Client offline. Emulating natural language command:", query);
    const emulated = emulateQueryResponse(query, currentWidgets, false);
    return res.json(emulated);
  }

  try {
    const systemPrompt = `
      You are the backend AI layout and analytics engine for "Gridify", a highly polished drag-and-drop telemetry dashboard.
      The user provides a natural language query: "${query}".
      
      Here is the current list of dashboard widgets:
      ${JSON.stringify(currentWidgets, null, 2)}
      
      Here is the raw telemetry data:
      ${JSON.stringify(defaultTelemetry, null, 2)}
      
      Your job is to respond in JSON format, containing:
      1. 'aiSummary': An array of 3-5 strings presenting concise, polished analytical bullet points or insights about the telemetry data relative to the query. Keep bullet points elegant, brief, and highly realistic.
      2. 'feedbackMessage': A clean, professional 1-sentence confirmation of what action you performed (e.g. "I've added a custom Sensor Voltage area chart to your dashboard.").
      3. 'newWidgets': (Optional) If the user asked to ADD a chart, CREATE a view, REMOVE a chart, or TOGGLE things, return the updated or newly designed array of widgets.
         - To ADD a widget: Create a new object with an ID like "custom_X", type: "custom_chart", title: a suitable title, subtitle: descriptive, w: 2 or 3, and a 'customData' object with 'labels' (array of strings), 'values' (array of numbers), and 'yAxisLabel' (string).
         - To REMOVE: filter out matching items from the currentWidgets list.
         - Otherwise, return currentWidgets or omit if no visual change is required.

      Keep the tone helpful, professional, and objective.
    `;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: systemPrompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            aiSummary: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: "Array of analytical insight statements or summaries."
            },
            feedbackMessage: {
              type: Type.STRING,
              description: "Brief user-facing confirmation of AI action taken."
            },
            newWidgets: {
              type: Type.ARRAY,
              description: "Updated widgets list if adding/removing/editing layout, otherwise leave empty or match original.",
              items: {
                type: Type.OBJECT,
                properties: {
                  id: { type: Type.STRING },
                  title: { type: Type.STRING },
                  subtitle: { type: Type.STRING },
                  type: { type: Type.STRING },
                  w: { type: Type.INTEGER },
                  h: { type: Type.INTEGER },
                  order: { type: Type.INTEGER },
                  customData: {
                    type: Type.OBJECT,
                    properties: {
                      labels: { type: Type.ARRAY, items: { type: Type.STRING } },
                      values: { type: Type.ARRAY, items: { type: Type.NUMBER } },
                      yAxisLabel: { type: Type.STRING }
                    }
                  }
                }
              }
            }
          },
          required: ["aiSummary", "feedbackMessage"]
        }
      }
    });

    const parsed = JSON.parse(response.text || "{}");
    res.json({
      aiSummary: parsed.aiSummary,
      feedbackMessage: parsed.feedbackMessage,
      newWidgets: parsed.newWidgets || currentWidgets,
      status: "Nominal"
    });

  } catch (error: any) {
    console.error("Gemini model execution error (falling back to local emulator):", error);
    // Graceful fallback during 503 / high-demand scenarios
    const fallbackResponse = emulateQueryResponse(query, currentWidgets, true);
    res.json(fallbackResponse);
  }
});

// Configure Vite middleware or production static folder
async function setupServer() {
  if (process.env.NODE_ENV !== "production") {
    console.log("Starting server in development mode with Vite middleware...");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    console.log("Starting server in production mode with static hosting...");
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Gridify server listening on http://localhost:${PORT}`);
  });
}

setupServer();
