"""Gemini AI integration endpoints for Gridify dashboard."""

import json
import logging
from typing import Dict, Any, List, Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from app.config import settings
from app.utils.logger import setup_logger
from app.utils.telemetry_data import get_default_telemetry
from app.services.gemini_service import GeminiService

logger = setup_logger(__name__)
router = APIRouter()

# Initialize Gemini service
gemini_service = GeminiService(api_key=settings.GEMINI_API_KEY)


class GeminiCommandRequest(BaseModel):
    """Request model for Gemini command."""
    query: str
    currentWidgets: List[Dict[str, Any]] = []


class GeminiCommandResponse(BaseModel):
    """Response model for Gemini command."""
    aiSummary: List[str]
    feedbackMessage: str
    newWidgets: List[Dict[str, Any]]
    status: str = "Nominal"


@router.post("/gemini/command")
async def handle_gemini_command(request: GeminiCommandRequest) -> GeminiCommandResponse:
    """Handle natural language command via Gemini AI.
    
    Args:
        request: Contains the natural language query and current widgets.
        
    Returns:
        GeminiCommandResponse with AI summary, feedback, and updated widgets.
        
    Raises:
        HTTPException: If query is missing or processing fails.
    """
    if not request.query:
        logger.error("Gemini command received without query")
        raise HTTPException(status_code=400, detail="Missing query string")

    # NOTE: prompt-injection guardrails now run in the async network layer
    # (see AsyncGuardrailMiddleware in app/middleware) so they stay off the
    # synchronous request path and don't delay time-to-first-token.

    logger.info(f"Processing Gemini command: {request.query}")
    
    try:
        # Get telemetry data
        telemetry = get_default_telemetry()
        
        # Try to use Gemini API
        if gemini_service.is_available():
            logger.info("Using Gemini API for command processing")
            response = await gemini_service.process_command(
                query=request.query,
                current_widgets=request.currentWidgets,
                telemetry=telemetry
            )
        else:
            logger.warning("Gemini API not available, using fallback emulation")
            response = _emulate_query_response(
                query=request.query,
                current_widgets=request.currentWidgets,
                is_fallback_mode=True
            )
        
        return GeminiCommandResponse(**response)
        
    except Exception as e:
        logger.error(f"Error processing Gemini command: {str(e)}")
        logger.info("Falling back to emulation mode")
        response = _emulate_query_response(
            query=request.query,
            current_widgets=request.currentWidgets,
            is_fallback_mode=True
        )
        return GeminiCommandResponse(**response)


def _emulate_query_response(
    query: str,
    current_widgets: List[Dict[str, Any]],
    is_fallback_mode: bool = False
) -> Dict[str, Any]:
    """Emulate natural language query response in offline/fallback mode.
    
    Args:
        query: Natural language query from user.
        current_widgets: Current dashboard widgets.
        is_fallback_mode: Whether running in fallback mode.
        
    Returns:
        Emulated response dictionary.
    """
    feedback_message = (
        "Gridify layout engine running in backup mode due to temporary upstream model load."
        if is_fallback_mode
        else "Configured layout and analyzed metrics successfully (Offline mode)."
    )
    
    new_widgets = list(current_widgets) if current_widgets else []
    ai_summary = [
        "Temperature trends show normal cyclical variance. Check peak loads during afternoon operations.",
        "Proxy devices maintain stable active flow control states with minor load offsets.",
        "Marchival Arc is exhibiting slightly higher average node temperature latency; investigate status indicator.",
    ]
    
    lower_query = query.lower()
    
    if any(keyword in lower_query for keyword in ["add", "chart", "create"]):
        widget_id = f"custom_{int(__import__('time').time() * 1000)}"
        new_widgets.append({
            "id": widget_id,
            "title": "Dynamic Telemetry: Sensor Voltage",
            "subtitle": "Generated by backup layout engine" if is_fallback_mode else "Generated by Gemini AI layout engine",
            "type": "custom_chart",
            "w": 2,
            "h": 300,
            "order": len(new_widgets) + 1,
            "customData": {
                "labels": ["00:00", "04:00", "08:00", "12:00", "16:00", "20:00"],
                "values": [3.3, 3.2, 3.4, 3.1, 3.5, 3.3],
                "yAxisLabel": "Volts (V)"
            }
        })
        feedback_message = (
            "Added dynamic Sensor Voltage chart (emulated fallback due to temporary model demand)."
            if is_fallback_mode
            else "Added a dynamic Sensor Voltage chart to the layout!"
        )
        ai_summary.insert(0, "Dynamic telemetry configured: Voltage levels average 3.3V, showing healthy battery load.")
        
    elif any(keyword in lower_query for keyword in ["remove", "delete"]):
        if len(new_widgets) > 2:
            removed = new_widgets.pop()
            feedback_message = f'Removed widget: "{removed.get("title", "Unknown")}" from the active workspace.'
        else:
            feedback_message = "Kept primary widgets to maintain minimum dashboard visualization integrity."
            
    elif any(keyword in lower_query for keyword in ["summarize", "analyse", "analyze"]):
        feedback_message = (
            "Completed telemetry load and uptime analysis (backup mode)."
            if is_fallback_mode
            else "Completed deeper telemetry load and uptime analysis."
        )
        ai_summary = [
            "Device load: Home Hub averages 2.3K loads with optimal 26.78 Sensor load values.",
            "System uptime is steady at 3h 10m aggregate uptime with zero hard reboots.",
            "No severe performance drops are registered for any of the 10 monitored operational nodes.",
        ]
    else:
        feedback_message = (
            f'Processed custom query: "{query}" (backup emulation)'
            if is_fallback_mode
            else f'Processed custom query: "{query}"'
        )
    
    return {
        "aiSummary": ai_summary,
        "feedbackMessage": feedback_message,
        "newWidgets": new_widgets,
        "status": "Nominal (Backup Mode)" if is_fallback_mode else "Nominal"
          }
  
